### ISSUE TITLE
Faker as API - fakend.fyi

### ISSUE THREAD

**Issue by sanjaykhanssk** [faker-js/awesome-faker#4]
Hi all, i have created this project [fakend.fyi ](https://fakend.fyi/)a free mock API tool basked on faker. I need your help to validate the product. I hope you guys will share reviews about the product.

**Comment by ST-DDT** [comment]
Please create a PR and add a link to the https://github.com/faker-js/awesome-faker#projects-using-faker-jsfaker list
If it is a commercial product please include a `(Commercial)` or similar suffix to your description.

**Comment by Shinigami92** [comment]
Please create a new headline between Projects and Languages called "Services"

I also like the `(Commercial)` 👍

**Comment by sanjaykhanssk** [comment]
File update in my local but can't commit(permission issue for user name 'sanjaykhanssk'). Is there any specific process I need to follow?
![image](https://github.com/faker-js/awesome-faker/assets/29035533/bc77abdd-fa23-4a12-9175-ae2c961d97f7)

**Comment by Shinigami92** [comment]
You can learn here https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/fork-a-repo?tool=cli about how GitHub Forks work
